### ISSUE TITLE
ENOENT: no such file or directory, scandir

### ISSUE THREAD

**Issue by shyjuck** [agrostar/zzapi-vscode#1]
Trying to run zzAPI on a Windows machine, by keeping the zzb file in the E: directory. Getting the below error while running the request. 

`A system error occurred (ENOENT: no such file or directory, scandir '/e:/Tools/zzAPI')`

**Comment by vasansr** [comment]
This was a bug in a previous version. Please check your version that is installed. The bug is fixed in v0.10.6.

**Comment by shyjuck** [comment]
This is resolved in the latest version. Thank you for the prompt response.
