### ISSUE TITLE
Support multiple bundles on CLI

### ISSUE THREAD

**Issue by gitblit** [agrostar/zzapi-vscode#12]
I'd like to be able to specify multiple bundles or maybe even a glob pattern on the CLI. My use-case is to maintain a `package.json` run script. It might also be good to output the bundle being tested in the console log.

```json
{
  "scripts": {
    "zzapi": "bunx zzapi-cli tests/01.zzb tests/02.zzb tests/03.zzb -e local",
    "zzapi": "bunx zzapi-cli tests/*.zzb -e local"
  }
}
```

**Comment by vasan-agrostar** [comment]
Shells are better at doing that. We were expecting you to write a shell script to iterate over the bundles. Further, glob patterns work differently in Windows vs Mac vs Linux.

We could definitely consider multiple bundles. Glob would have to be resolved by the shell, though.

**Comment by gitblit** [comment]
Multiple bundles would be perfect for my use-case.
