### ISSUE TITLE
Have you tried running CLI on Bun?

### ISSUE THREAD

**Issue by gitblit** [agrostar/zzapi-vscode#13]
Have you tried running on Bun? That is pretty much my go-to these days. The CLI does not run on Bun - and it may be a Bun bug which I can report to them, but I can't diagnose what's wrong to make a meaningful report.

```
bunx zzapi-cli tests.zzb -e local # runs in Node
bunx --bun zzapi-cli tests.zzb -e local # runs in Bun
```

When I run the second one with Bun, the CLI outputs this:

```
5/21/2024, 8:15:28 PM [ERROR] GET List Test Error executing request: Attempted to assign to readonly property.)
```

Any idea where to start looking?

**Comment by vasan-agrostar** [comment]
Oh. We're sorry. We have no clue about bun. The error message may be a clue. At the moment, we don't have enough bandwidth to support bun.

**Comment by gitblit** [comment]
That's reasonable. I'll try to look into this over the weekend and see if I can figure out from where the message originates.

**Comment by gitblit** [comment]
I cloned the CLI & the core library.  Got the CLI building and was able to run it from a pure build with Bun using `tests-bundle.zzb` from the zzapi examples. 🤔

I then went back to my app repo and started playing around. TL;DR it looks like the latest release of Bun (1.1.9) fixed some Node compatibility bugs and this now works perfectly. 🎉 

As they hype, code runs a lot faster & yields the same results. Just sharing this in case it interests you.

```
time node ./dist ../zzapi/examples/tests-bundle.zzb
# Node 18.17 (old, I know) output omitted
real 0m5.736s

time bun ./dist ../zzapi/examples/tests-bundle.zzb
# Bun 1.1.9 (latest) output omitted
real 0m1.494s
```
