### ISSUE TITLE
Regression on status checks

### ISSUE THREAD

**Issue by gitblit** [agrostar/zzapi-vscode#18]
We seem to have lost status checks. Looks like they have been excluded somehow.

<img width="595" alt="image" src="https://github.com/agrostar/zzapi-vscode/assets/868217/071a7cdf-59b3-44c5-814f-d1145487a73f">

**Comment by Varun0157** [comment]
The test was being run, but the result was not being pushed into the `SpecResult` instance. Fixed. 

We will have to make a new release for the same, and bump up the versions of the CLI runner and VSCode Extension @vasan-agrostar.
