### ISSUE TITLE
URL and sub URL

### ISSUE THREAD

**Issue by shyjuck** [agrostar/zzapi-vscode#2]
Is there any provision to provide a main URL (till root context) for the entire requests and the sub URL should be mentioned within each requests ?

**Comment by Varun0157** [comment]
Yes, you can provide a baseUrl in common, and then assign url's per request. Check out the [bundle specification](https://github.com/agrostar/zzapi/blob/main/zzapi-bundle-description.md) for all functionality. The url in the individual requests get appended to the baseUrl if they start with a /. 

Also check out the [the tests bundle in zzapi-core](https://github.com/agrostar/zzapi/blob/main/tests-bundle.zzb) for an example of the same.
