### ISSUE TITLE
Automated tests using Jest

### ISSUE THREAD

**Issue by vasan-agrostar** [agrostar/zzapi-vscode#20]
Forking this issue from #14 

> In support of these changes, assuming some proposal moves forward, can we leverage Jest to validate whatever implementation is selected? [#18](https://github.com/agrostar/zzapi-vscode/issues/18) is a good example of something that would have been caught with some test automation and these changes will be difficult to validate if the project keeps moving ahead with manual QA.

We do have some automated tests in zzapi-cli but it is a copy of the manual tests in zzapi. Not sure why the tests did not catch the regression. @Varun0157 is it because postman endpoints have changed?

Let us move the automated tests to zzapi:

* Have some way of specifying that we expect a negative test to fail (maybe the request has to have 'negative' in it)
* Or separate the bundles into two: one for positive and the other for negative tests.
* Just as the CLI does, go through the motions of calling the APIs to run the requests and tests. Instead of printing the test results in the console, we assert against the number of tests that have passed/failed.

**Comment by vasan-agrostar** [comment]
Or we could add a `doc` element against each test/spec to indicate whether it is expected to pass or fail. But we don't parse the doc fields right? Maybe we should do that too. It could be useful for other runners who use zzapi.

**Comment by Varun0157** [comment]
The tests did not catch the status assertions missing because of [this](https://github.com/agrostar/zzapi-vscode/issues/16?notification_referrer_id=NT_kwDOB4EcXbUxMTAwMjM4NzQ4MzoxMjU5MDE5MTc#issuecomment-2169178129). Although, any tests we do write at the moment may not pass (or rather, behave as expected) because of the postman-echo endpoints changing as you mentioned.
