### ISSUE TITLE
Reporting of $size failure can be more accurate

### ISSUE THREAD

**Issue by vasansr** [agrostar/zzapi-vscode#22]
When a `$size` test fails, we report the expected value as the given count, but we print the entire array as "got". For large arrays, this is inconvenient.

```
[FAIL] test $.responseData.productGists: expected $size: 60 | got [{...}, {...} ...]
```

I'd rather see the size of the array that we got:

```
[FAIL] test $.responseData.productGists: expected $size: 60 | 39
```
I can always look at the actual result in the output, but counting the number of array elements in the output is hard.

**Comment by Varun0157** [comment]
Do we want to do this for all size related clauses (`$lt`, `$gt`, `$lte`, `$gte`, `$eq`, `$ne`) as well as the direct comparison, or only for a direct comparison (i.e., `received : expected`)?

**Comment by vasansr** [comment]
Yeah. Essentially, we want to say expected > 5, got 3, or expected == 5, got 7 etc.

The "received" should follow what is expected. If the entire array was expected, the received should also print that. If only the size of the array was expected, we should print the size of the array received.
