### ISSUE TITLE
Ability to convert request URI or cURL request to zzAPI request

### ISSUE THREAD

**Issue by vasansr** [agrostar/zzapi-vscode#23]
I find myself often pasting the contents of a request from, say nginx logs or when someone sends me the cURL request.

Example:

```
/catalogservice/v3/productwarehouseinventory/?skuCodes=AGS-AV-001,AGS-CP-1227,AGS-CP-1228,AGS-S-4509&facilityCode=JDH01
```

It would be nice if I could just paste this, select the text, right click on the text and convert it to a GET request.

Or a cURL request in toto:
```
curl 'https://example.com/service/v3/endpoint/?userId=573236' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'source: B2BUP' \
  -H 'x-authorization-token: XXXX
```

POST requests are going to be hard to deconstruct, plus I don't usually feel the need for this in POST requests.

**Comment by Varun0157** [comment]
For curl requests, we'll have to look into adding another dependency to parse it right? [curlconverter](https://www.npmjs.com/package/curlconverter) seems widely used for this. For regular URI's we can probably use node's in built `url` module. 

- Should we use these dependencies for the same? 
- What should the created request be named?

**Comment by vasansr** [comment]
With the curlconverter and the jsontoyaml extension I am able to do this (though it takes two steps). I think this will suffice. Let us not implement the same in zzAPI.
