### ISSUE TITLE
"undefined" status when connection refused

### ISSUE THREAD

**Issue by vasansr** [agrostar/zzapi-vscode#25]
I thought it used to work before, but I can't see a proper error message when the connection is refused.

<img width="609" alt="Screenshot 2024-07-07 at 11 58 08 AM" src="https://github.com/agrostar/zzapi-vscode/assets/6049234/fc087bf7-fe11-4ca5-b661-01ebd49028e9">

<img width="230" alt="Screenshot 2024-07-07 at 11 58 32 AM" src="https://github.com/agrostar/zzapi-vscode/assets/6049234/b05b432b-a6b1-46b7-ba21-ee9210276485">

It doesn't break anything, but it would be nice to show the error as returned by got.

**Comment by vasan-agrostar** [comment]
Fixed in zzapi 2.0.1, zzapi-vscode 2.4.1, zzapi-cli 3.2.1
