### ISSUE TITLE
Miscellaneous considerations for request tests

### ISSUE THREAD

**Issue by gitblit** [agrostar/zzapi-vscode#3]
Thanks for offering this tool to the community! I've been playing around with it to see if it satisfies my needs and I've hit a few minor snags.

Basic:
- Cannot use `$gt`, `$gte`, `$lt`, `$lte` operators on array size. Arrays can only be asserted for exact sizing. Ideally I'd like more flexibility on testing array sizes. ```$.items: { $exists: true, $type: array, $size: { $gt: 5 } }```
- I'd like to see `status` and `$h` tests run first, _always_. Currently if you define those in `common` they appear to be appended to the endpoint test list and run last. Perhaps prepend the common tests (in the order defined by the user) to the endpoint test list OR perhaps sort status & header tests first, regardless of where they are defined?
- If `status` or `$h` tests fail, the `$.` body tests are likely to fail since the response shapes or types will be different than expected. Perhaps do not run `$.` tests if the status and/or `$h.` tests fail? I have example endpoints where 400 or 403 responses return strings instead of application/json and this creates noise when zzzapi attempts to parse JSON in these cases.
- I am using `$regex`, but have you considered `$startsWith`, `$endsWith`, and `$contains` as simpler alternatives?

Advanced:
- Have you considered a declaration to skip tests? Could be as simple as ```skip: true``` or more sophisticated like ```skip: { $os: { $eq: "Windows" } }```
- ThunderClient offers some compelling [array indexing tricks](https://docs.thunderclient.com/testing/array-testing). I'm not sure if those are JSONPath compliant or not, but they are convenient.
- Have you considered a mechanism to drop down to javascript asserts/tests when basic ones do not suffice?

**Comment by vasan-agrostar** [comment]
Thanks. Each of the points makes a lot of sense. I had some of these in mind but had not acted.

I will add a separate issue for each of the points because we can address some of them immediately but some others may take time.

**Comment by vasan-agrostar** [comment]
Need clarification for #7

**Comment by gitblit** [comment]
Excellent! Thanks for the consideration @vasan-agrostar!
