### ISSUE TITLE
Option to skip tests

### ISSUE THREAD

**Issue by vasan-agrostar** [agrostar/zzapi-vscode#7]
Forked off from issue #3 

- Have you considered a declaration to skip tests? Could be as simple as ```skip: true``` or more sophisticated like ```skip: { $os: { $eq: "Windows" } }```

**Comment by vasan-agrostar** [comment]
@gitblit can you please elaborate on this need? I am not able to appreciate the use case here.

The philosophy we wanted to follow in zzAPI is to not over-engineer and use the editor itself to achieve many things. If you like to temporarily disable the tests, you could just comment them out and uncomment them when you are done.

**Comment by gitblit** [comment]
That's true; commenting-out or deleting is indeed a reasonable approach. Having the ability to declare something skipped is a matter of taste. In my case I don't want to comment-out (we have a policy against this practice) nor to delete (makes the test vanish). I'd like to be able to declare the test as skipped and have that acknowledged by the test runner in the logged output. In this way it is a constant reminder that it should be addressed. Maybe there is an intermittent bug in the endpoint that is blocking CI-CD from completing and we need to temporarily bypass this test to unblock the rest of the team but at the same time we do not want to introduce garbage (hunk of comments) or delete the test.
```
5/7/2024, 7:50:24 AM [SKIPPED] GET Some Endpoint Test
```

This is a typical feature of testing frameworks (junit, jest, xunit, etc). I don't have a specific use-case for sophisticated conditions, boolean is sufficient for my needs. This is also not a must-have feature for me, so if this request contradicts zzapi's ideals, then "skip" it. :)

**Comment by vasan-agrostar** [comment]
I am wondering how to specify the skip on a per-test basis. Some thoughts:

```
tests:
  $.some.nested.path: { $eq: 42, $skip: true } # cannot use $.some.nested.path: 42, forced to use { $eq }
  status: { $lte: 299, $skip: true } # For $lte etc, we anyway need this object
  ...
```
or
```
tests:
  x$.some.nested.path: 42 # any test starting with x will be skipped
  xstatus: 42 # not very obvious for the reader, but very succinct
```
Thoughts, @gitblit ?

**Comment by gitblit** [comment]
I like the attribute/property over the prefix convention.

```
{ $eq: 42, $skip: true }
```
