### ISSUE TITLE
Advanced array indexing tricks like ThunderClient

### ISSUE THREAD

**Issue by vasan-agrostar** [agrostar/zzapi-vscode#8]
Forked off from issue #3 

- ThunderClient offers some compelling [array indexing tricks](https://docs.thunderclient.com/testing/array-testing). I'm not sure if those are JSONPath compliant or not, but they are convenient.

**Comment by vasan-agrostar** [comment]
The ThunderClient array indexing tricks all have JSONPATH equivalents. Since we don't evaluate the path within zzAPI ourselves and rely only on jsonpath, we can only support what jsonpath does.

Take, for example, this ThunderClient example:
```
json.items[type$="Food"].type
```

Using JSON path, this is what you would do to achieve the same:
```
$.items[?(@.type.endsWith('Food'))].type
```

**Comment by gitblit** [comment]
Thanks for this information. 💪 I'll read more about JSONPath.

**Comment by vasan-agrostar** [comment]
Resources you may find useful:

1. https://jsonpath.com/
2. https://goessner.net/articles/JsonPath/index.html#e2
